#
# ~/.config/bash/bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

export HISTFILE="$XDG_STATE_HOME"/bash/history

export GPG_TTY=$(tty)
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye > /dev/null
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
